insert into companies (name, est_year) values ('Realpoint', 1984);
insert into companies (name, est_year) values ('Shufflebeat', 2001);
insert into companies (name, est_year) values ('Twitternation', 1985);
insert into companies (name, est_year) values ('Nlounge', 1992);
insert into companies (name, est_year) values ('Plambee', 2004);

insert into departments (name, company_id) values ('Engineering', 3);
insert into departments (name, company_id) values ('Human Resources', 5);
insert into departments (name, company_id) values ('Training', 1);
insert into departments (name, company_id) values ('Research and Development', 3);
insert into departments (name, company_id) values ('Business Development', 3);
insert into departments (name, company_id) values ('Training', 3);
insert into departments (name, company_id) values ('Accounting', 5);
insert into departments (name, company_id) values ('Legal', 5);
insert into departments (name, company_id) values ('Engineering', 2);
insert into departments (name, company_id) values ('Support', 5);
insert into departments (name, company_id) values ('Human Resources', 1);
insert into departments (name, company_id) values ('Research and Development', 1);
insert into departments (name, company_id) values ('Business Development', 2);
insert into departments (name, company_id) values ('Research and Development', 3);
insert into departments (name, company_id) values ('Research and Development', 4);
insert into departments (name, company_id) values ('Marketing', 1);
insert into departments (name, company_id) values ('Support', 4);
insert into departments (name, company_id) values ('Product Management', 2);
insert into departments (name, company_id) values ('Training', 4);
insert into departments (name, company_id) values ('Legal', 3);

insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Anna-diane', 'Banbrook', 48, 'abanbrook0@huffingtonpost.com', 'woman', 5, 13);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Ceciley', 'Bundey', 40, 'cbundey1@google.ru', 'man', 1, 3);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Foss', 'Tappington', 24, 'ftappington2@1688.com', 'woman', 8, 12);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Kellina', 'Reihill', 20, 'kreihill3@usatoday.com', 'man', 5, 17);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Miquela', 'Ackerley', 20, 'mackerley4@time.com', 'man', 6, 17);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Frederique', 'Regus', 40, 'fregus5@nytimes.com', 'man', 14, 4);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Napoleon', 'Muzzlewhite', 48, 'nmuzzlewhite6@delicious.com', 'man', 5, 9);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Murray', 'Wilcox', 45, 'mwilcox7@census.gov', 'woman', 5, 15);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Guthrie', 'Shirlaw', 51, 'gshirlaw8@columbia.edu', 'woman', 1, 3);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Noll', 'Mash', 45, 'nmash9@imageshack.us', 'woman', 14, 5);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Charmine', 'Wheatley', 40, 'cwheatleya@youtu.be', 'man', 1, 18);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Artemis', 'Bennellick', 45, 'abennellickb@wix.com', 'man', 20, 5);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Moritz', 'Klammt', 45, 'mklammtc@home.pl', 'woman', 4, 5);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Toby', 'Pillans', 51, 'tpillansd@usatoday.com', 'man', 12, 15);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Yorgo', 'St Clair', 20, 'ystclaire@bloglovin.com', 'man', 1, 10);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Angelique', 'Larderot', 40, 'alarderotf@disqus.com', 'woman', 8, 14);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Goldy', 'Tampion', 48, 'gtampiong@yahoo.com', 'man', 8, 2);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Benedicto', 'Fitzsimmons', 45, 'bfitzsimmonsh@phpbb.com', 'woman', 2, 9);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Heddi', 'Gowman', 32, 'hgowmani@msn.com', 'woman', 14, 16);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Blancha', 'Conichie', 59, 'bconichiej@tripadvisor.com', 'woman', 8, 14);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Sande', 'Marians', 48, 'smariansk@zimbio.com', 'woman', 5, 18);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Jeniffer', 'Doneld', 27, 'jdoneldl@yelp.com', 'woman', 3, 5);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Obadiah', 'Kleinstern', 34, 'okleinsternm@cbsnews.com', 'man', 12, 12);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Nadia', 'Muddimer', 51, 'nmuddimern@tinyurl.com', 'woman', 20, 6);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Stavros', 'McKew', 45, 'smckewo@soundcloud.com', 'man', 4, 9);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Lucius', 'Ronca', 48, 'lroncap@bizjournals.com', 'woman', 8, 18);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Lillian', 'Frangione', 32, 'lfrangioneq@smh.com.au', 'man', 1, 13);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Gery', 'Paterno', 20, 'gpaternor@drupal.org', 'man', 2, 1);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Beryl', 'Macauley', 34, 'bmacauleys@icio.us', 'man', 20, 12);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Waite', 'Pretty', 27, 'wprettyt@desdev.cn', 'man', 8, 18);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Chester', 'Lamacraft', 40, 'clamacraftu@dailymail.co.uk', 'man', 12, 2);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Lusa', 'Crossfield', 20, 'lcrossfieldv@webs.com', 'man', 5, 18);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Worth', 'Dreher', 45, 'wdreherw@dmoz.org', 'man', 6, 11);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Rufus', 'Mowne', 48, 'rmownex@indiegogo.com', 'woman', 14, 19);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Eirena', 'Stainland', 48, 'estainlandy@cbc.ca', 'man', 2, 1);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Chucho', 'Chatteris', 27, 'cchatterisz@weibo.com', 'woman', 1, 8);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Randa', 'Lynnett', 45, 'rlynnett10@ocn.ne.jp', 'woman', 2, 11);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Maiga', 'Lacroutz', 34, 'mlacroutz11@forbes.com', 'man', 20, 14);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Amelia', 'Mosten', 40, 'amosten12@wp.com', 'woman', 6, 12);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Terry', 'Pickance', 45, 'tpickance13@last.fm', 'woman', 6, 19);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Ricard', 'Rossbrook', 45, 'rrossbrook14@hp.com', 'woman', 4, 9);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Corilla', 'Gonzales', 32, 'cgonzales15@linkedin.com', 'man', 6, 18);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Glad', 'Saurat', 32, 'gsaurat16@dyndns.org', 'woman', 1, 3);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Ethelbert', 'Perell', 59, 'eperell17@gov.uk', 'woman', 4, 14);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Dionisio', 'Simco', 27, 'dsimco18@hugedomains.com', 'man', 1, 17);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Ellie', 'Pady', 40, 'epady19@biblegateway.com', 'man', 5, 7);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Jolyn', 'Sheeres', 27, 'jsheeres1a@cnbc.com', 'woman', 3, 10);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Rebeca', 'Krauze', 20, 'rkrauze1b@noaa.gov', 'man', 5, 14);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Ruprecht', 'Clynman', 45, 'rclynman1c@youtu.be', 'woman', 6, 6);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Jaynell', 'Lehmann', 59, 'jlehmann1d@google.it', 'woman', 4, 15);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Horace', 'Dasent', 20, 'hdasent1e@yelp.com', 'man', 4, 19);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Meagan', 'Brand', 24, 'mbrand1f@noaa.gov', 'woman', 14, 20);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Angelo', 'Timlin', 51, 'atimlin1g@123-reg.co.uk', 'man', 6, 14);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Zachery', 'Drysdale', 34, 'zdrysdale1h@godaddy.com', 'man', 5, 4);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Wat', 'Germain', 24, 'wgermain1i@globo.com', 'man', 12, 13);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Mella', 'Glewe', 27, 'mglewe1j@ebay.co.uk', 'woman', 4, 9);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Karim', 'Dislee', 27, 'kdislee1k@theglobeandmail.com', 'woman', 5, 3);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Karlene', 'Deegan', 51, 'kdeegan1l@yahoo.co.jp', 'man', 4, 11);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Norine', 'O''Crigan', 20, 'nocrigan1m@twitter.com', 'man', 6, 4);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Ddene', 'Livingston', 45, 'dlivingston1n@infoseek.co.jp', 'woman', 12, 9);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Miof mela', 'Sefton', 51, 'msefton1o@theatlantic.com', 'woman', 12, 4);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Elaina', 'Terne', 24, 'eterne1p@yandex.ru', 'man', 6, 16);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Etienne', 'Glanvill', 27, 'eglanvill1q@ebay.co.uk', 'woman', 3, 15);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Jordanna', 'Joslow', 34, 'jjoslow1r@house.gov', 'woman', 6, 18);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Benedicta', 'Dore', 51, 'bdore1s@usnews.com', 'man', 12, 15);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Nehemiah', 'Edworthie', 45, 'nedworthie1t@toplist.cz', 'woman', 3, 1);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Estella', 'Cavalier', 45, 'ecavalier1u@hc360.com', 'woman', 6, 3);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Tremaine', 'Mayler', 59, 'tmayler1v@soundcloud.com', 'woman', 20, 5);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Marylin', 'Pidon', 51, 'mpidon1w@sfgate.com', 'man', 6, 12);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Brent', 'Pawlicki', 45, 'bpawlicki1x@adobe.com', 'woman', 20, 15);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Lowrance', 'Eddow', 45, 'leddow1y@mlb.com', 'woman', 3, 8);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Eveleen', 'Shiril', 48, 'eshiril1z@marriott.com', 'man', 1, 20);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Franchot', 'Molan', 27, 'fmolan20@shareasale.com', 'woman', 1, 12);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Karel', 'Sayton', 59, 'ksayton21@slate.com', 'woman', 8, 3);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Skylar', 'Fritschel', 20, 'sfritschel22@creativecommons.org', 'man', 8, 5);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Terri', 'Brake', 51, 'tbrake23@globo.com', 'man', 1, 1);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Gloriane', 'Lideard', 40, 'glideard24@blogtalkradio.com', 'woman', 1, 2);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Durand', 'Kares', 32, 'dkares25@redcross.org', 'woman', 8, 2);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Jordana', 'Venning', 51, 'jvenning26@wired.com', 'woman', 1, 1);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Tally', 'Crawshay', 59, 'tcrawshay27@blogs.com', 'woman', 8, 4);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Auroora', 'Ballaam', 40, 'aballaam28@bigcartel.com', 'man', 5, 7);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Ly', 'Pavlitschek', 34, 'lpavlitschek29@fda.gov', 'woman', 12, 3);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Mariquilla', 'Pickerin', 45, 'mpickerin2a@behance.net', 'woman', 14, 18);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Gorden', 'Kuban', 59, 'gkuban2b@bing.com', 'woman', 14, 13);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Penn', 'de Clerq', 27, 'pdeclerq2c@hud.gov', 'woman', 8, 15);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Christi', 'Adamovich', 20, 'cadamovich2d@cdc.gov', 'man', 2, 2);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Garreth', 'Aughtie', 45, 'gaughtie2e@smh.com.au', 'man', 8, 16);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Darryl', 'Daoust', 32, 'ddaoust2f@examiner.com', 'man', 4, 17);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Bria', 'Cowsby', 48, 'bcowsby2g@webnode.com', 'man', 8, 17);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Launce', 'Sherrocks', 20, 'lsherrocks2h@wisc.edu', 'woman', 6, 4);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Pia', 'Bonnor', 24, 'pbonnor2i@wikipedia.org', 'woman', 5, 12);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Pia', 'Moule', 32, 'pmoule2j@un.org', 'woman', 4, 3);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Lucita', 'Jorge', 24, 'ljorge2k@harvard.edu', 'man', 8, 4);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Rich', 'Rajchert', 48, 'rrajchert2l@bbc.co.uk', 'man', 6, 2);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Gennifer', 'Hubbard', 45, 'ghubbard2m@behance.net', 'man', 1, 2);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Dianne', 'Dunford', 51, 'ddunford2n@rakuten.co.jp', 'woman', 3, 15);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Daphene', 'Joncic', 48, 'djoncic2o@cbc.ca', 'woman', 1, 20);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Louisa', 'Hanks', 40, 'lhanks2p@list-manage.com', 'man', 2, 12);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Cash', 'Nussey', 59, 'cnussey2q@europa.eu', 'woman', 20, 18);
insert into employees (first_name, last_name, age, email, gender, experience, department_id) values ('Cchaddie', 'Guppy', 20, 'cguppy2r@slideshare.net', 'man', 8, 15);
